### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by juzhiyuan** [trekhleb/javascript-algorithms#1]
Hello, Can I try to translate the repo to Chinese?

**Comment by trekhleb** [comment]
Hello @juzhiyuan

Sure! You may create localized README files in the same folders with original READMEs and put proper locale to file extensions. For example **README.zh-CN.md** or **README.zh-TW.md** or other locale. And then you’re welcome to create a PR.

**Comment by trekhleb** [comment]
Ok :) So then this issue may be closed I assume
