### ISSUE TITLE
confusing insertion and deletion time complexity on linked list

### ISSUE THREAD

**Issue by happyuniv** [trekhleb/javascript-algorithms#1001]
on [linked-list page](https://github.com/trekhleb/javascript-algorithms/tree/master/src/data-structures/linked-list) and [doubly-linked-list page](https://github.com/trekhleb/javascript-algorithms/tree/master/src/data-structures/doubly-linked-list) 
time complexity on insertion is O(1) but on deletion is O(n) 
Why is it different? shouldn't deletion be O(1) or insertion be O(n) ?

**Comment by lazarljubenovic** [comment]
Insertion assumes appending to head/tail, so no traversal happens. Deletion means deleting a specific node, so you need to find it firstly.

**Comment by vikash18o19** [comment]
@lazarljubenovic 
Exactly, In case of Insertion:  I guess we have both the pointers, the head and the tail, had it been just the head, We would need to traverse the whole list to insert at the end and complexity would have been O(n).
In case of deletion: as @lazarljubenovic mentioned we need to find the node first. thus, O(n).
Issue: #1001 must have been resolved now.
