### ISSUE TITLE
Rename `QuickSortInPlace` to `TrueQuickSort` or something similar.

### ISSUE THREAD

**Issue by farkaskid** [trekhleb/javascript-algorithms#105]
It should be mentioned that `QuickSortInPlace` is the actual quick sort. Other implementation that allows using extra space is like quick sort but not the strictly the actual algorithm.

I've seen this at several places. For example the following implementation of quicksort in Haskell
```
quicksort :: (Ord a) => [a] -> [a]  
quicksort [] = []  
quicksort (x:xs) =   
    let smallerSorted = quicksort [a | a <- xs, a <= x]  
        biggerSorted = quicksort [a | a <- xs, a > x]  
    in  smallerSorted ++ [x] ++ biggerSorted  
```
It is shown as a quicksort implementation but in reality it is not.
A lot of newbies will get a wrong idea about the quicksort this way who are only learning algos this way.
It should at least be mentioned in the ReadMe that the one with the in-place is the real one.

**Comment by trekhleb** [comment]
Thank you for your issue @farkaskid 
I've updated READMEs and mentioned your point there.
