### ISSUE TITLE
How to use the repository

### ISSUE THREAD

**Issue by CFCIfe** [trekhleb/javascript-algorithms#1058]
Knowing how to use the repository should be before the explanation of problems in this repository on the README file

**Comment by lazarljubenovic** [comment]
What isn't clear on how to "use" it?

**Comment by trekhleb** [comment]
"How to use repo" is available in README https://github.com/trekhleb/javascript-algorithms#how-to-use-this-repository. The list of algorithms, arguablym seems like more important to mention first
