### ISSUE TITLE
Translate to Polish

### ISSUE THREAD

**Issue by pavelekpl** [trekhleb/javascript-algorithms#111]
Hi, can I translate the README.md to Polish? Thanks.

**Comment by trekhleb** [comment]
Hi @pavelekpl 
Sure!
Please name the file with Polish translation as README.pl-PL.md and place it alongside with main README.md file. If you want to translate all subfolders then just do the same and create subfolders README.pl-PL.md files.

**Comment by pavelekpl** [comment]
Alright, thanks!

**Comment by trekhleb** [comment]
Thank you for translation @pavelekpl
