### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by seIncorp** [trekhleb/javascript-algorithms#122]
Please add correct description for javascript-algorithms/src/data-structures/linked-list/LinkedList.js, because comment in Delete function is misleading:
// If the head must be deleted then make 2nd node to be a head.

It would be better to add:
'while' will delete all nodes with the same value, starting with the this.head.

**Comment by seIncorp** [comment]
And wrong name of delete function.

Reason:
name means to delete one node in the list and not all nodes with the same value.

**Comment by trekhleb** [comment]
I've updated the comment before `while`. The `delete` function name still seems to reasonable since consumer of this function shouldn't know implementation details (whether it was one or many nodes that have been deleted).
