### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by viestat** [trekhleb/javascript-algorithms#123]
I believe it would be nice to translate the README.md to Spanish and would love to help!

**Comment by trekhleb** [comment]
Sure @viestat! If you're willing to contribute Spanish translation then just create another **REAME.es-ES.md** alongside with main README.md and put your translation there.

**Comment by AnibalFlores** [comment]
[javascript-algorithms-spanish-translation.zip](https://github.com/trekhleb/javascript-algorithms/files/2257953/javascript-algorithms-spanish-translation.zip)
Hola @trekhleb ! I done it, hope you like.

**Comment by agusnavce** [comment]
I have submited a PR for the translation.

**Comment by trekhleb** [comment]
Thanks @agusnavce !
I'm closing this issue then.
