### ISSUE TITLE
AVL tree does not rebalance after removal

### ISSUE THREAD

**Issue by w8r** [trekhleb/javascript-algorithms#13]
Hi! Thanks for your project. I can't seem to find the removal algorithm in AVL tree: if it simply borrows the binary tree removal, it's incomplete. I was particularly interested in that, cause I have been looking for a removal procedure that doesn't mutate the nodes.

Cheers.

**Comment by huzaima** [comment]
Is it still open for contribution?

**Comment by trekhleb** [comment]
@huzaima yes it is open. You might want to take a look at https://github.com/trekhleb/javascript-algorithms/pull/33 PR and cooperate with @Bladefidz to make it green.

**Comment by Bladefidz** [comment]
Hi @trekhleb and @huzaima, I am free at this weekend.

I will push some commits soon.

**Comment by arslan-ashraf** [comment]
Hey guys, I see the AVL tree still hasn't been fixed.  I know how to make work.  I would love to make a contribution to the repo but I don't have permission.

**Comment by trekhleb** [comment]
Removal is fixed now.
