### ISSUE TITLE
the picture about Red-Black Tree is not match

### ISSUE THREAD

**Issue by sputnikW** [trekhleb/javascript-algorithms#132]
see **javascript-algorithms/src/data-structures/tree/red-black-tree/readme.md**
There are four pictures describe the red-black tree's four cases(LL /LR /RR /RL).But the `Right Right Case` and the `Right Left Case` 's picture are the same.

**Comment by trekhleb** [comment]
Thanks for noticing that @sputnikW ! It is fixed now.
