### ISSUE TITLE
Needs Pseudocode?

### ISSUE THREAD

**Issue by moshejs** [trekhleb/javascript-algorithms#143]
I'm thinking of adding pseudocode to the readme based on [DSA by Granville Barnett and Luca Del Tongo](http://lib.mdp.ac.id/ebook/Karya%20Umum/Dsa.pdf). Would this be useful?

**Comment by trekhleb** [comment]
Hi @moshejs , thank you for suggestion!
Yes you may try to add pseudocodes to specific READMEs. Let's have one or two PRs to see how it would work if you will.

**Comment by moshejs** [comment]
Posted one for linked list @trekhleb if you like it, I will add more

**Comment by trekhleb** [comment]
@moshejs thank you for PR! Yes please add more if you want. 

Just few minor comments on the PR.
- Indentation: let's use 2 spaces
- Code block: let's use triple ` signs.
- Complexities: let's use tables for data-structures basic operations.

I've made these small correctness for linked list here https://raw.githubusercontent.com/trekhleb/javascript-algorithms/master/src/data-structures/linked-list/README.md just for example.
