### ISSUE TITLE
Add Max Heap? 

### ISSUE THREAD

**Issue by bresson** [trekhleb/javascript-algorithms#145]
A Max Heap DS would be terrific in this repo. Should I work on it and submit a PR? I'm also open to other DS or algorithm contributions.

**Comment by trekhleb** [comment]
@bresson yes, please, just feel free add MaxHeap if you want.

I think it should be added in the same folder as MinHeap. We would need to have an AbstractHeap.js class that will be a base class for the MinHeap.js and MaxHep.js just to avoid code duplication. What do you think?

**Comment by bresson** [comment]
@trekhleb Sounds great! I'll work on a AbstractHeap and MaxHeap first and get a PR, then circle back to refactor MinHeap to inherit from the AbstractHeap. 

Quick clarification, Java has dedicated Abstract classes so in JS we're thinking along the lines of following Java's abstract template - a base class which cannot be instantiated and will have abstract and non-abstract methods?

**Comment by trekhleb** [comment]
@bresson yeah, unfortunately we will need to _imitate_ abstractness. I was thinking about something like this:

```javascript
class Heap {
  constructor() {
    if (new.target === Heap) {
      throw new TypeError('Cannot construct Heap instance directly');
    }
  }

   // Methods that are common for both Min and Max heaps.
}

class MinHeap extends Heap {
  constructor() {
    super();
  }

  // MinHeap specific methods here.
}
```

Something like that. Just to avoid code duplication. Maybe it is even not abstractness but rather a parent class that just may not be instantiated.

**Comment by bresson** [comment]
Sounds great - aiming for PR in about a week unless work interferes.

**Comment by okersov** [comment]
Hi @bresson, I started to implement MaxHeap before this issue is created.
I have prepared PR https://github.com/trekhleb/javascript-algorithms/pull/167
but I will change it according to the @trekhleb comment above.

**Comment by trekhleb** [comment]
Thanks for PR @okersov
