### ISSUE TITLE
Test suite failed to run on Ubuntu

### ISSUE THREAD

**Issue by okersov** [trekhleb/javascript-algorithms#169]
Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

**Comment by okersov** [comment]
Solution: https://github.com/facebook/jest/issues/6769
PR: https://github.com/trekhleb/javascript-algorithms/pull/170

**Comment by trekhleb** [comment]
Thanks for the fix @okersov
