### ISSUE TITLE
heap remove function has bug

### ISSUE THREAD

**Issue by watchsky** [trekhleb/javascript-algorithms#179]
https://github.com/trekhleb/javascript-algorithms/blob/872a38fac6ee2d8df7adac9dbab625e5965cf4cc/src/data-structures/heap/Heap.js#L178

`!` should be removed . The test case is that min heap [1,2,3,4,5,6,7,8,9] remove 2 and should be expected '1,4,3,8,5,6,7,9' but get '1,9,3,4,5,6,7,8' with the wrong code.

**Comment by trekhleb** [comment]
@watchsky good catch! Thank you.
