### ISSUE TITLE
while focus the element page not get scrolled in firefox and ie

### ISSUE THREAD

**Issue by synckarthik** [trekhleb/javascript-algorithms#190]
I have tried to focus the element in my page using focus method. When the element is focusing, page scrolled automatically in to the focused element. But In firefox and IE browsers page not scrolled properly. So my focused element visible in bottom of the page.

Sample: https://www.w3schools.com/code/tryit.asp?filename=FUQUWTPT2PVU

Steps: Run the sample in chrome, element will be appear in middle of the page. In Firefox it will appear in bottom of the page.

How to resolve it?

**Comment by trekhleb** [comment]
Hi @synckarthik 
Looks like the issue is not connected to algorithms repo.
