### ISSUE TITLE
some error comment in src/queue/Queue.js

### ISSUE THREAD

**Issue by GHLandy** [trekhleb/javascript-algorithms#192]
I'm new to learn Data Structure. When I read src/queue/Queue.js as the follow, it really confuse me.
And then I realize that the comment should note deleting the first node (head).

![image](https://user-images.githubusercontent.com/14830914/44898768-69374500-ad32-11e8-82d9-35ad50966072.png)

**Comment by trekhleb** [comment]
Fixed by @appleJax
