### ISSUE TITLE
I have a question in shell-sort README.md

### ISSUE THREAD

**Issue by sam-dingkang** [trekhleb/javascript-algorithms#195]
after gap = 2, compare and swap the values, why not [14, 10, 27, 19, 35, 33, 42, 44]，but
![image](https://user-images.githubusercontent.com/15643321/44951333-6eaca080-ae94-11e8-9475-96d81c990ed9.png)

thanks

**Comment by trekhleb** [comment]
@sam-dingkang yes, you're right. There is a typo on the picture. I've added additional link to YouTube video with more explanation of ShellSort and also put a comment below the picture you've addressed.
