### ISSUE TITLE
Suggestion: using memoization for computation heavy functions

### ISSUE THREAD

**Issue by nnIIInnjA** [trekhleb/javascript-algorithms#197]
we can use memoization for functions like fibonacci, so that we don't calculate again for already calculated number.
I'd love to create a PR. thanks

**Comment by trekhleb** [comment]
Hi @nnIIInnjA, thank you for suggestion. But we already use memoization for fibonacci. I guess the following piece of code can be treated as memoization, can't it?

```javascript
currentValue += previousValue;
previousValue = currentValue - previousValue;
```

**Comment by nnIIInnjA** [comment]
No, I meant if someone uses fibonacci code in prod. like this
`var value = fibonacci(20)
var val = fibonacci(20)`.
 the code shouldn't calculate the value again as we can store calculated value for 20 using memoize.

**Comment by nnIIInnjA** [comment]
Yup, Got it. thanks much.
