### ISSUE TITLE
console.log(42 / +0); // Infinity
console.log(42 / -0); // -Infinity


### ISSUE THREAD

**Issue by Aya-arch-prog** [trekhleb/javascript-algorithms#2033]

**Comment by Aya-arch-prog** [comment]
> (spole)

**Comment by lazarljubenovic** [comment]
Spole schmole

**Comment by Sbonelo01** [comment]
Hkgkgfleclelfrjegejfhfghh
Bkfjfjggff discussions yuiu for yotd
Fjuusfjsjdjdkdk CV dlzhehrk so far I'll
djdlejskdjdgdkdbsksvalkjsjsksksjskdjsjdjsjsjsjsjdjdjdhdkjkchcbvvbdjdbdjdjbbbdnwgjevejdhdjdjjdjdjdjfjfjfndhdjfhhfhj
Nknhdorgkfhfjfjfjfnfnfnfbdjhdvdjdhe8dhdhhdhdhdhhdhfhf
Bkdhejdjdjdjfjfjfhhhhfkfhfkfkvrlrgkfohddfdhjdghjhgghhhcjgwjvkgjcjwnvwnwjwjwjwhjwjwkvwwkwlwhwcwjwjwjwkwj
Hjjhgu,,,,,,fzysyduphohohogxhxvcjvjvjvjvjvjgugigifigigigztsyfoguxtzigifyxtkstdoyditutitaisozorsotarsruarsfsjchchchxyx🇿🇦4💓💋💋🇿🇦💓💔💞💓💓💞💔💔💔💋💓💋❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️💋7💞77💋
Co Iyazi but I don't A TOPICS PENDEMICAL PUBLIC STRESSING you want me to
watch it where you at least khona ezinye izingane lapho bbe ngicela kungabi
nalutho noma
