### ISSUE TITLE
automated test suite

### ISSUE THREAD

**Issue by dalssoft** [trekhleb/javascript-algorithms#21]
a suggestion for improve quality, readability and robustness of the algorithms is to have test cases. 

without tests it is hard to know if the algorithms / data structure works as intended.

**Comment by robtaussig** [comment]
Which algorithms don't have test cases? I haven't looked at all of them, but each one that I have appears covered

**Comment by dalssoft** [comment]
sorry. i hadn't find the _test_ dir.
