### ISSUE TITLE
TSP or TPP Algorithm

### ISSUE THREAD

**Issue by dfliess** [trekhleb/javascript-algorithms#22]
I'm looking for any implementation of Multiple Travelers Purchase Problem, any idea ?

**Comment by Zaseth** [comment]
With a simple Google search I already found what you need.

(tsp algorithm javascript)

**Comment by dfliess** [comment]
thanks I've also done that search but none of them seems to resolve Multiple travelers, maybe Id didn't look well and you can elighten me.
