### ISSUE TITLE
Images of `AVL Tree Rotations` not accessible

### ISSUE THREAD

**Issue by RequireSun** [trekhleb/javascript-algorithms#264]
![image](https://user-images.githubusercontent.com/7576691/49699458-6d65df00-fc0c-11e8-9f59-b0dc5c1dc6e9.png)

**Comment by lazarljubenovic** [comment]
Well this issue is certainly not accessible either :smile:

**Comment by RequireSun** [comment]
emmm...now there's only one image not accessible

![image](https://user-images.githubusercontent.com/7576691/49714904-ae500900-fc89-11e8-9d2e-9761f67963fb.png)

**Comment by trekhleb** [comment]
It should be fixed now.
