### ISSUE TITLE
Possible mistake in README for Bit Manipulation section.

### ISSUE THREAD

**Issue by vtange** [trekhleb/javascript-algorithms#287]
In the very last section (for the isPowerOfTwo method)
```
Number: 4 = 0b0100
Number: 3 = (4 - 1) = 0b0011
4 & 3 = 0b0100 & 0b0011 = 0b0000 <-- Equal to zero, is power of two.

Number: 10 = 0b01010
Number: 9 = (10 - 1) = 0b01001
10 & 9 = 0b01010 & 0b01001 = 0b01000 <-- Not equal to zero, not a power of two.
```

The last line seems to claim 0b01000  is not a power of two even though it is. Running the function as a Chrome snippet ( isPowerOfTwo(0b01000) ) also returns true. What exactly does the last line mean?

**Comment by yash0530** [comment]
Hello @vtange  
There is no mistake in README, the algorithm says if a given number here 10 which is 0b01010 is a power of 2 then after (10 - 1) & 10 this transformation if output is 0 then it is power of 2  

As explained in the README (10 - 1) & 10 != 0, hence it (10) is not a power of two

**Comment by trekhleb** [comment]
As @yash0530 stated,  the line `10 & 9 = 0b01010 & 0b01001 = 0b01000` doesn't mean that `0b01000` is not a power of `2`. It means that `10` is not a power of `2` because `10 & (10 - 1)` is not equal to zero.
