### ISSUE TITLE
Add Red Black Tree

### ISSUE THREAD

**Issue by Bladefidz** [trekhleb/javascript-algorithms#29]
Hello,

I have once write Red Black Tree in Java and interesting to write another version in Javascript. Anyone have already working on it? If no one, maybe I will pull the Red Black Tree tonight.

Regard,
Hafidz

**Comment by trekhleb** [comment]
Thank you for your interest @Bladefidz !
I'm currently working in Red Black Tree implementation.

**Comment by trekhleb** [comment]
Red-black tree was added.
Please find implementation here https://github.com/trekhleb/javascript-algorithms/tree/master/src/data-structures/tree/red-black-tree.

It lack remove method so far though.

**Comment by Bladefidz** [comment]
Ok @trekhleb, will catch it in next week. By the way, our implementation is so different. I will try to adapt your design.
