### ISSUE TITLE
I can't require npm package in node application

### ISSUE THREAD

**Issue by wolffles** [trekhleb/javascript-algorithms#295]
is anyone else having this problem? I tried `const data = require('javascript-algorithms-and-data-structure');` and it throws an error in my node server, says "Error: Cannot find module 'javascript-algorithms-and-data-structure'" it's installed using npm install 'javascript-algorithms-and-data-structure'

**Comment by alexframe** [comment]
Because `javascript-algorithms-and-data-structure` [is not an npm package](http://npmjs.com/package/javascript-algorithms-and-data-structure).

You need to [clone the repository and then just `npm install`](https://github.com/trekhleb/javascript-algorithms#how-to-use-this-repository).

**Comment by trekhleb** [comment]
@wolffles yes, as @alexframe stated you can't use this repo as npm package. For now it works only with forking/cloning.
