### ISSUE TITLE
Fibonacci sequences

### ISSUE THREAD

**Issue by ohepworthbell** [trekhleb/javascript-algorithms#30]
Not an issue - more of a suggestion. Would be good to return an array for the fibonacci sequence, as well as the sequence at nth position (and maybe rename the nth-position `fibonacciNth()` or something). For example:

```JavaScript
export default function fibonacci(steps) {
  const fibSequence = [];

  let currentValue = 1;
  let previousValue = 0;

  if(steps === 1) {
    return [1];
  }

  while(steps--) {
    currentValue += previousValue;
    previousValue = (currentValue - previousValue);

    fibSequence.push(currentValue);
  }

  return fibSequence;
}
```

And:

```JavaScript
export default function fibonacciNth(steps) {
  let currentValue = 1;
  let previousValue = 0;

  if(steps === 1) {
    return 1;
  }

  while(steps--) {
    currentValue += previousValue;
    previousValue = (currentValue - previousValue);
  }

  return currentValue;
}
```

Also, where before there was a:

```JavaScript
while(iterationsCounter) {
  // Do code
  
  iterationsCounter -= 1;
}
```
This is mildly verbose, and can be more succinctly written without detriment to legibility as:

```JavaScript
while(iterationsCounter--) {
  // Do code
}
```
Personally I think that's more readable. Happy to do a PR?

_Edit: camel cased variable names to match existing code_

**Comment by trekhleb** [comment]
@ohepworthbell thank you for suggestion!
Yes please just create a PR.

**Comment by ohepworthbell** [comment]
Great, pull request created! Had to revert the `iterationsCounter` to the original loop as [JSLint doesn't seem to allow unary operators](https://eslint.org/docs/rules/no-plusplus)

**Comment by trekhleb** [comment]
Fixed in https://github.com/trekhleb/javascript-algorithms/pull/36

**Comment by hdcorder147** [comment]
Stop
