### ISSUE TITLE
find(key) always returns null

### ISSUE THREAD

**Issue by bobmugura** [trekhleb/javascript-algorithms#303]
https://github.com/trekhleb/javascript-algorithms/blob/6fe7df339a76c3a1ce9be3aac5a1b2b2eeb52e4c/src/data-structures/doubly-linked-list/DoublyLinkedList.js#L129

I have a DoublyLinkedList like [1, 2, 3, 4] and each integer represents DoublyLinkedListNode. When I try to use find(1), it returns -1. I also noticed the function arguments such as { key, callback } and I was thinking the callback portion is optional. How can I find a node with value of 1 using this find function?

**Comment by trekhleb** [comment]
@bobmugura, try to use `find({ value: 1 })` instead.
