### ISSUE TITLE
Spelling mistake in readme of levenshtein-distance 

### ISSUE THREAD

**Issue by anilkumarnandamuri** [trekhleb/javascript-algorithms#311]
The spelling of the "Sunday" is mentioned as "Sanday" in the example grid of Saturday and Sunday in readme file of levenshtein-distance.

![lev_distance](https://user-images.githubusercontent.com/5524296/52904789-b1192e00-31e5-11e9-942c-47ef686c4d47.png)

**Comment by nirvanarsc** [comment]
I also noticed this. Please use the edited image below
![68747470733a2f2f63646e2d696d616765732d312e6d656469756d2e636f6d2f6d61782f313630302f312a67654d646d5a63645531625a6248496f68364b4f33512e706e67](https://user-images.githubusercontent.com/1153337/54865681-9457b380-4dac-11e9-959a-01c8ca00a85f.png)

**Comment by trekhleb** [comment]
@nirvanarsc, thank you for the fix!
