### ISSUE TITLE
QuickSortInPlace: bug in performance measuring code.

### ISSUE THREAD

**Issue by haalogen** [trekhleb/javascript-algorithms#312]
Hey guys,

https://github.com/trekhleb/javascript-algorithms/blob/1f393551c72c4559f17766ab54f4758fe3752ac8/src/algorithms/sorting/quick-sort/QuickSortInPlace.js#L49

`pivot` is meant to be a _value_, isn't it?
Shouldn't it be

```js
 this.callbacks.visitingCallback(array[highIndex]); 
```
or
```js
 this.callbacks.visitingCallback(pivot); 
```
instead?

This change is also proposed in: #239

**Comment by trekhleb** [comment]
@haalogen yes, you're right. Thank you for the fix!
