### ISSUE TITLE
Test description typo in PriorityQueue.test.js

### ISSUE THREAD

**Issue by iamlockon** [trekhleb/javascript-algorithms#315]
As title, it appears to me that the test description in [line 37](https://github.com/trekhleb/javascript-algorithms/blob/master/src/data-structures/priority-queue/__test__/PriorityQueue.test.js#L37) : 
```javascript
  it('should be possible to change priority of internal nodes', () => {
```
and in line 54 : 
```javascript
  it('should be possible to change priority of head node', () => {
```
 should be exchanged, since the node with item of value '100' should be the head node in my opinion. Thank you.

**Comment by trekhleb** [comment]
@iamlockon I guess you're right. The naming should be fixed now.
