### ISSUE TITLE
Sharing similar effort: algorithms-js

### ISSUE THREAD

**Issue by ManrajGrover** [trekhleb/javascript-algorithms#34]
Hi @trekhleb,

This is one amazing project. Thank you for working on it.

I just wanted to quickly share a similar effort I made last year for building a consumable algorithms and data structure library. I did heavily test it. I hope this might help someone.

https://github.com/ManrajGrover/algorithms-js

Maybe, we can link it in README somewhere?

**Comment by trekhleb** [comment]
Hi @ManrajGrover 

Good job with https://github.com/ManrajGrover/algorithms-js!

Regarding adding the link in README I think you should better create pull-request to the repository that is specialized on that (on collecting links to great projects). I mean this one https://github.com/tayllan/awesome-algorithms. There you may find collection of algorithms related useful links.

The purpose of current repository is a little bit different.
Anyways thank you for your suggestion!
