### ISSUE TITLE
Pseudocode for Delete is wrong (LinkedList)

### ISSUE THREAD

**Issue by brandonvilla21** [trekhleb/javascript-algorithms#344]
## Problem
[Delete](https://github.com/trekhleb/javascript-algorithms/tree/master/src/data-structures/linked-list#delete) pseudocode is wrong for what I can see. However the code works since is a different implementation than the one shown in pseudocode.

## Explanation
Bellow I point the piece of pseudocode I believe is wrong, or at least it won't work for a specific case:
```
Remove(head, value)
  ...
  if n.next != ø
    if n.next = tail
      tail ← n (X)
    end if
    n.next ← n.next.next
    return true
  end if
  return false
end Remove
```
When you remove the last value of the linked list (the tail) it will execute the line marked with an `X`
In that line, basically the tail will point to the previous value, the problem is that `n (the previous value)` is still pointing to the Node to be removed and n is being assigned to `tail`, therefore the value won't be completly removed and will cause unexpected behavior when you want to append more Nodes to the Linked list

## Solution
Add this to the pseudocode:
```
Remove(head, value)
  ...
  if n.next != ø
    if n.next = tail
      tail ← n
      tail.next = ø (Just one line 😃)
    end if
    n.next ← n.next.next
    return true
  end if
  return false
end Remove
```
This way you will unlink the last Node, the one you want to remove

**Comment by biaspro** [comment]
Wouldn't `n.next ← n.next.next` make the new tail point to `ø`?
