### ISSUE TITLE
A suggestion about Factorial

### ISSUE THREAD

**Issue by Jeffrey1029** [trekhleb/javascript-algorithms#40]
Not an issue - more of a suggestion.  Is it better to start the loop from 2？
```
export default function factorial(number) {
  let result = 1;

  for (let i = 2; i <= number; i += 1) {
    result *= i;
  }

  return result;
}
```

**Comment by nikhilakudikala** [comment]
Because the factorial of 0 and 1 is always 1 and the function returns 1 if the number is less than 2.
Yes, its better to start the loop from 2 as long as the number is a positive integer.

**Comment by trekhleb** [comment]
Thank you for your comment @Jeffrey1029 
It is fixed now.
