### ISSUE TITLE
npm run lint gives error

### ISSUE THREAD

**Issue by Veeloxfire** [trekhleb/javascript-algorithms#440]
What I did: Clone respository. Navigate to repository using cmd. Run npm install.
Finds 2943 vulnerabilities.
Whether or not I ignore this doesnt affect the lint part.
Run npm run lint in the same directory.
Get Error with ESLint: 6.0.1, 6.0.0 and 5.3.0:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! javascript-algorithms-and-data-structures@0.0.4 lint: `eslint ./src/*`
npm ERR! Exit status 2

Id really like to fix this as I have a bug fix but I cant do a pull request as npm run lint never succeeds

**Comment by Veeloxfire** [comment]
Was able to fix this by running on ESLint 5.3.0 and changing package.json to have ./src/** Then adding .eslintignore for all the README.md files because it didnt like the '#' characters in them. 
This is a temporary fix I'm sure I'm missing something obvious but this was all I could do it get it working

**Comment by denizbinay** [comment]
Ran into the same trouble. I made a german translation but I can't pass the test. I didn't change anything in the code. Has something new come out here?

https://github.com/trekhleb/javascript-algorithms/issues/683
