### ISSUE TITLE
Linked List need a insertion operation.

### ISSUE THREAD

**Issue by Trendymen** [trekhleb/javascript-algorithms#499]
In many other tutoral in C language, i can see a LinkedList's insertion operation implement or thinking. Why can't js have that too?

**Comment by sidou01** [comment]
LinkedList already has 2 insert operations. One is prepend which inserts the node at the beginning and it becomes the head and the other is append which inserts the node at the end and it becomes the tail.

**Comment by Trendymen** [comment]
> LinkedList already has 2 insert operations. One is prepend which inserts the node at the beginning and it becomes the head and the other is append which inserts the node at the end and it becomes the tail.

but what i mean was that insert operation can insert a node to linkedlist by given index.
