### ISSUE TITLE
There is a spelling mistake. It should be "grandParent" not "granParent"

### ISSUE THREAD

**Issue by crown3** [trekhleb/javascript-algorithms#528]
https://github.com/trekhleb/javascript-algorithms/blob/929b210b8e02cd77bdc3575a4e897ad24ad64ad3/src/data-structures/tree/red-black-tree/RedBlackTree.js#L158

**Comment by Aloneduckling** [comment]
hello, I want to help by solving a small issuesto start. I know JS. Can I contribute

**Comment by lazarljubenovic** [comment]
Try not randomly hijacking issues to ask that.

**Comment by Aloneduckling** [comment]
What do you mean hijacking

**Comment by trekhleb** [comment]
The fix is merged to the `master` branch.
