### ISSUE TITLE
Fucking Awesome !

### ISSUE THREAD

**Issue by Turkyden** [trekhleb/javascript-algorithms#53]
Nice, it is so useful for us !

**Comment by trekhleb** [comment]
@Turkyden I'm glad that you like it! :)
If you don't mind I'll close this issue because of absence of action plan

**Comment by mdsaleemj** [comment]
Hi @trekhleb , I just to want to understand the code in depth, do you have any reference to study while looking at your code. Do you follow any books /material ?

**Comment by Turkyden** [comment]
@trekhleb OK, no problem.

**Comment by trekhleb** [comment]
@mdsaleemj 
I haven't follow any book. All the sources I've read I've put in each algorithm's README. But I heard from my friend about the "Algorithms unlocked" book by Thomas H. Cormen. You may try this one, maybe you'll like it. I haven't read it so far.
