### ISSUE TITLE
Opening for Full Stack JS Developer

### ISSUE THREAD

**Issue by SergB38** [trekhleb/javascript-algorithms#539]
Hello, Igor!
I`ve checked your profile and I can see you work with Javascript. 
Our company has very interesting opportynity, please send me a message vie indicated email to discuss it. 
Have a great day!

Sergiy,
e-mail: bichurin.sergiy@gmail.com

**Comment by lazarljubenovic** [comment]
What the shit

**Comment by votrannghia** [comment]
Dear !

At present, I am in progress of practicing JS.

Thank you!

Vào Th 7, 12 thg 9, 2020 vào lúc 17:29 Oleksii Trekhleb <
notifications@github.com> đã viết:

**Comment by lazarljubenovic** [comment]
Is this some new kind of bots?

**Comment by SergB38** [comment]
No,it isn`t bots) It`s real proposition/
Is it interesting for you?

Regards,

Sergiy Bichurin



IT Recruiter

*Mediastream AG*

*M* +380632264882

*Web*: www.mediastream.ag

*E*: bichurin.sergiy@gmail.com

*E*: katrin.pakina@mediastream.ag


сб, 12 сент. 2020 г. в 14:41, Lazar Ljubenović <notifications@github.com>:

**Comment by trekhleb** [comment]
Hey folks, let's keep the "Issues" section of the repo for the repository related issues, not for HR-related issues.
