### ISSUE TITLE
Getting every possible shortest path between two nodes

### ISSUE THREAD

**Issue by anand-010** [trekhleb/javascript-algorithms#563]
Getting every possible shortest path between two nodes using dijkstra algorithm ( ranked by best path ). Any one getting javascript code that would be awesome.

**Comment by azozello** [comment]
@trekhleb Hi, I would like to work on this issue if it will add value. Also I would be happy to help with any other issue

**Comment by anand-010** [comment]
I am working on a public transportation application. I need to rank every path ranked by first came bus ( By Calculating Bus velocity and route distance). I am looking to calculate this information on Node.js server. I have created an adjacency matrix of route connections. I want to find all possible path between user-entered stops. if you help me that would be great.

(Optional)
am also want to find the smallest route when there is even some gap between stops ( user need to walk some distance to get next bus ).
** I am a College student and I am not expert in any algorithm

**Comment by anand-010** [comment]
@trekhleb and @azozello Please help me.

**Comment by lostnco1** [comment]
Ok

**Comment by anand-010** [comment]
everyone forgets about this?
