### ISSUE TITLE
Data structures and algorithms 

### ISSUE THREAD

**Issue by Got-crypto** [trekhleb/javascript-algorithms#576]
I'm a begginer at data structures and algorithms, I wonder if there was anyone that could help me go through it

**Comment by sparkidea25** [comment]
When you find any, let me know 🙏🙏

**Comment by lazarljubenovic** [comment]
Just ask a question when you have a concrete one.

**Comment by Got-crypto** [comment]
Thanks for reaching out

**Comment by trekhleb** [comment]
Hi @Got-crypto
Unfortunately, the `Issues` section of this repo isn't a proper place to general questions. I would suggest you to come up with exact questions and try StackOverflow or something similar. Closing this issue for now.
