### ISSUE TITLE
How to cite this repository

### ISSUE THREAD

**Issue by ahmaruff** [trekhleb/javascript-algorithms#579]
I need to cite this repo for my paper.

I found another github repo provide guideline to cite their repo. (See below)

> Zhang, A. (2017). Speech Recognition (Version 3.8) [Software]. Available from https://github.com/Uberi/speech_recognition#readme.

Can I write citation similar like this? Or do you have any sugestion?

**Comment by fitrahmunir** [comment]
hi ahmarrhi ahmaruff, you can check this post https://academia.stackexchange.com/a/14015

but i suggest ask your lecture first, because most of university has rules

**Comment by ahmaruff** [comment]
Thanks for your advice👍

**Comment by fitrahmunir** [comment]
your welcome and good luck
