### ISSUE TITLE
Linked List - Purpose of Callback Function

### ISSUE THREAD

**Issue by halitaydin** [trekhleb/javascript-algorithms#625]
Hello folks,

I need to know purpose of callback function in find method in linked-list class. Is that callback function require for usage or not so important? If yes, how can i use it?
I have searched other sites and books but not find any solution.

Thank you for your helps.
<img width="516" alt="LinkedList find method" src="https://user-images.githubusercontent.com/64103256/104631197-fafa3f80-56ac-11eb-91bd-968f264d4358.png">

**Comment by josesanchez-hotmart** [comment]
Reading the tests, the callback works as a custom constraint you apply to find an element in the linked list; as a function, it should return true for the elements you want to find. Check [here](https://github.com/trekhleb/javascript-algorithms/blob/master/src/data-structures/linked-list/__test__/LinkedList.test.js#L172) to see how it works.

**Comment by halitaydin** [comment]
Thank you Jose, now everything is clear.
