### ISSUE TITLE
Assignment operation on the 'else' block not need in KMP

### ISSUE THREAD

**Issue by saranshdhingra** [trekhleb/javascript-algorithms#631]
On line 53, we have:
`wordIndex = 0;`
but this else block is reached only when wordIndex is already infact 0.

https://github.com/trekhleb/javascript-algorithms/blob/83357075c4698f487af733e6e0bf9567ba94c266/src/algorithms/string/knuth-morris-pratt/knuthMorrisPratt.js#L53

We should remove from the source.

**Comment by yogeshpanchal8195** [comment]
Can I get this issue to resolve efficiently
