### ISSUE TITLE
Grouping algorithms for studying

### ISSUE THREAD

**Issue by BraveVN** [trekhleb/javascript-algorithms#70]
Thank you for creating this repo, it's awesome.
I just have one small question, can you divide all algorithms into group of level like: Beginner, Intermediate, Advance , etc so someone like students or newbies know where to start?

**Comment by trekhleb** [comment]
Thank you for suggestions @BraveVN 
I've added `A` and `B` marks for each algorithm that stand for **B**dvanced and **B**eginner.
