### ISSUE TITLE
Why not upload to npm?

### ISSUE THREAD

**Issue by lukasdiegelmann** [trekhleb/javascript-algorithms#706]
I would be glad to use this repository if it was uploaded to npm. That way it would be easier for me to handle it instead of downloading the whole code and putting it into my normal source directory. It just isn't clean. Also a quick npm publish does not normally take so long to do.

I do not see the problem. If I am missing something here, please inform me about it.

**Comment by bulknor99-ship-it** [comment]
> I would be glad to use this repository if it was uploaded to npm. That way it would be easier for me to handle it instead of downloading the whole code and putting it into my normal source directory. It just isn't clean. Also a quick npm publish does not normally take so long to do.
> 
> I do not see the problem. If I am missing something here, please inform me about it.

**Comment by lazarljubenovic** [comment]
There's no point. You shouldn't use any of these functions in your other projects. They are for learning purposes only. To play around, clone the repository.
