### ISSUE TITLE
Algorithm learning 

### ISSUE THREAD

**Issue by regzz15** [trekhleb/javascript-algorithms#753]

**Comment by elvanr** [comment]
Yes of course

**Comment by elvanr** [comment]
I'm going to spam everyone if you guys don't get me out of this...

**Comment by elvanr** [comment]
I've unsubscribed and still getting this shit

**Comment by elvanr** [comment]
Zabre

**Comment by trasherdk** [comment]
@elvanr Try figuring out which option to choose. It's really not that hard :rofl: 
![image](https://user-images.githubusercontent.com/5003891/130549828-26e2463d-cfd7-49dd-9cb7-900aa3432ec8.png)
