### ISSUE TITLE
I need an HTML, css and JavaScript calculator code pls

### ISSUE THREAD

**Issue by godsbrick** [trekhleb/javascript-algorithms#764]

**Comment by soyReynald** [comment]
You can write me on facebook or my twitter:

@soyReynald it's my twitter. I can help you with that code.

**Comment by Maikaelj** [comment]
> 

I can help with that

**Comment by namanjain2001-code** [comment]
i already made a calculator as personal project with css , js , and html.
 so i thing i can help.

**Comment by msboffl** [comment]
@namanjain2001, @Maikaelj -  How can I contact you .??

**Comment by ParseDark** [comment]
I can help on frontend Part

**Comment by JeffEsteves** [comment]
https://www.makeuseof.com/build-a-simple-calculator-using-html-css-javascript/

You can find 1 here. Hope it can help. If you would like something more specific let us know.
