### ISSUE TITLE
run repo's class? nodejs not support ES6 import

### ISSUE THREAD

**Issue by thiscodeohmygod** [trekhleb/javascript-algorithms#78]
i want to wirte a js to test a data-structures class ,as queue, but this js file can't run on lastest version nodejs? how can i run my test?

**Comment by trekhleb** [comment]
To run tests for **Queue** data-structure simply launch the following command from the root folder of javascript-algorithms project locally:

```
npm test -- -t 'Queue'
```

Also remember that you need to install node modules before running the tests:

```
npm i
```
