### ISSUE TITLE
JS algoritm

### ISSUE THREAD

**Issue by Sel-K** [trekhleb/javascript-algorithms#811]

**Comment by GITHUBGUY12357999** [comment]
hi

**Comment by MaximAnatolievic** [comment]
Hi15:33, 10 декабря 2021 г., GITHUBGUY12357999 ***@***.***>:
hi

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by GITHUBGUY12357999** [comment]
ok

**Comment by GITHUBGUY12357999** [comment]
HI

**Comment by GITHUBGUY12357999** [comment]
Do you have any approvals that I can do for you all?

**Comment by GITHUBGUY12357999** [comment]
We have this issue,




https://ci6.googleusercontent.com/proxy/WgxNMJ9zyyiDZXUXiHtrX2esLyYSZ-1UrMsU3TguafU86GTpW1VBz5MtJO9dw-16mD6B6iVOGc5qAi_4L91Dl2MB3-TpmISiRs-sZOZqpip0eWdKjAwgfZ4Pj7Ukl-v3jEcw5UJhCREw-rpH5cBbTgHVKdZVminS=s0-d-e1-ft#https://user-images.githubusercontent.com/48426139/148021857-3c4be7d5-22f3-45b9-9975-9b893bccea90.png



A big problem he is not able to do anything


This is under DEMO_TOOL
