### ISSUE TITLE
issue while running program 

### ISSUE THREAD

**Issue by Krish-bhardwaj** [trekhleb/javascript-algorithms#840]
Hi i dont know why but i am not able to run your program , i am new to js please help me 

```
Error
> javascript-algorithms-and-data-structures@0.0.4 test ......\javascript-algorithms
> jest "-t" "playground"

'jest' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```
![image](https://user-images.githubusercontent.com/72294477/150628218-2cf76283-a12e-49b1-b4d3-e6445d74b958.png)

**Comment by abhinav1602** [comment]
have you installed jest already using npm install jest command?
If yes, it is likely in your ./node_modules/.bin directory.
try `npm test -- --updateSnapshot` 
this will add  ./node_modules/.bin to path automatically.

**Comment by Krish-bhardwaj** [comment]
![image](https://user-images.githubusercontent.com/72294477/150631730-acd461a5-2e0c-44b3-bdaa-8252f24bf8e9.png)

why am i getting this error?

**Comment by trasherdk** [comment]
Update `npm` by running `npm -g i npm` as root.

Your installed version of `node` is probably also seriously outdated. Run `node -v && npm -v` to show installed versions.

**Comment by saukumar95** [comment]
> Hi i dont know why but i am not able to run your program , i am new to js please help me
> 
> ```
> Error
> > javascript-algorithms-and-data-structures@0.0.4 test ......\javascript-algorithms
> > jest "-t" "playground"
> 
> 'jest' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! Test failed.  See above for more details.
> ```
> 
> ![image](https://user-images.githubusercontent.com/72294477/150628218-2cf76283-a12e-49b1-b4d3-e6445d74b958.png)

Can you check if you have Jest installed properly in your system.
You can try reinstalling it through npm.

**Comment by ccknaus** [comment]
I am also new to JS, and I very much suffer playing around with the repository. Although alltests suffice, how I am suppose to run playground.js or any other .js file, created by me?

Whenever I run playground.js in VSC tells me:
`(node:9600) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`

But when I change `package.json` by adding a line `"type": "module",` I get another error:
`Error [ERR_MODULE_NOT_FOUND]: Cannot find module ... `
