### ISSUE TITLE
logo_web_dev

### ISSUE THREAD

**Issue by ghost** [trekhleb/javascript-algorithms#849]
![webdev](https://user-images.githubusercontent.com/58113633/152649054-b1292ff8-1e5e-48dc-be6e-f832b7c689f1.jpg)

**Comment by milleniait** [comment]
Join the All New Cross chain project Dogelana $DGLN.

Doge and Solana introduces the best and fastest Network on Blockchain.
Join us to partake in our IEO/ICO/NFT GIVEAWAY

https://t.me/+ZtYF6PzehrMxYmE0
