### ISSUE TITLE
Add doubly linked list

### ISSUE THREAD

**Issue by huzaima** [trekhleb/javascript-algorithms#87]
Shouldn't there be doubly linked list too?

If yes, can I contribute for it?

**Comment by trekhleb** [comment]
Hello @huzaima 
Yes, we may have a separate class for DoublyLinkedList. This class at least must contain all public methods of LinkedList just to have uniform way of using both of them. Thank you for suggestion!

**Comment by huzaima** [comment]
@trekhleb I'm starting work on this.

**Comment by huzaima** [comment]
Hey @andela-anandaa, check the [PR](https://github.com/trekhleb/javascript-algorithms/pull/92) I submitted for this. Kindly let me know if anything can be improved.

**Comment by trekhleb** [comment]
Thank you for the fix @huzaima
