### ISSUE TITLE
removeChild in BinaryTreeNode does not remove parent from child

### ISSUE THREAD

**Issue by flurmbo** [trekhleb/javascript-algorithms#98]
Apologies if this is the expected behavior. In BinaryTreeNode.js, the function removeChild sets either this.left or this.right to null, but does not set nodeToRemove.parent to null. So for example the following test fails:

```javascript
const rootNode = new BinarySearchTreeNode('foo');
rootNode.insert('bar');
const childNode = rootNode.find('bar');
rootNode.remove('bar');
expect(childNode.parent).toBeNull();
```

**Comment by trekhleb** [comment]
Thanks for noticing that @flurmbo . It is fixed now.
